version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: local
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    command: redis-server --port 6380
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - '6380:6380'